# Generated by Django 4.0.1 on 2022-01-26 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_alter_receita_redendimento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='redendimento',
            new_name='rendimento',
        ),
    ]
